spring.application.name=spotbus-backend
spring.datasource.url=jdbc:postgresql://db.kkxrjaqocspytavbspmu.supabase.co:5432/spotbus?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=oy3zRvS9iA5h2DHT
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=spotbus
